# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/cmake-gui

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/sakib/remoll/cosmic/CosmicRayShower

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/sakib/remoll/cosmic/CosmicRayShower

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/cmake-gui -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip
.PHONY : install/strip/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/sakib/remoll/cosmic/CosmicRayShower/CMakeFiles /home/sakib/remoll/cosmic/CosmicRayShower/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/sakib/remoll/cosmic/CosmicRayShower/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named cosmicRayShower

# Build rule for target.
cosmicRayShower: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cosmicRayShower
.PHONY : cosmicRayShower

# fast build rule for target.
cosmicRayShower/fast:
	$(MAKE) -f CMakeFiles/cosmicRayShower.dir/build.make CMakeFiles/cosmicRayShower.dir/build
.PHONY : cosmicRayShower/fast

#=============================================================================
# Target rules for targets named cosmics

# Build rule for target.
cosmics: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cosmics
.PHONY : cosmics

# fast build rule for target.
cosmics/fast:
	$(MAKE) -f CMakeFiles/cosmics.dir/build.make CMakeFiles/cosmics.dir/build
.PHONY : cosmics/fast

cosmicRayShower.o: cosmicRayShower.cc.o
.PHONY : cosmicRayShower.o

# target to build an object file
cosmicRayShower.cc.o:
	$(MAKE) -f CMakeFiles/cosmicRayShower.dir/build.make CMakeFiles/cosmicRayShower.dir/cosmicRayShower.cc.o
.PHONY : cosmicRayShower.cc.o

cosmicRayShower.i: cosmicRayShower.cc.i
.PHONY : cosmicRayShower.i

# target to preprocess a source file
cosmicRayShower.cc.i:
	$(MAKE) -f CMakeFiles/cosmicRayShower.dir/build.make CMakeFiles/cosmicRayShower.dir/cosmicRayShower.cc.i
.PHONY : cosmicRayShower.cc.i

cosmicRayShower.s: cosmicRayShower.cc.s
.PHONY : cosmicRayShower.s

# target to generate assembly for a file
cosmicRayShower.cc.s:
	$(MAKE) -f CMakeFiles/cosmicRayShower.dir/build.make CMakeFiles/cosmicRayShower.dir/cosmicRayShower.cc.s
.PHONY : cosmicRayShower.cc.s

src/cosmicsEventGenerator.o: src/cosmicsEventGenerator.cc.o
.PHONY : src/cosmicsEventGenerator.o

# target to build an object file
src/cosmicsEventGenerator.cc.o:
	$(MAKE) -f CMakeFiles/cosmicRayShower.dir/build.make CMakeFiles/cosmicRayShower.dir/src/cosmicsEventGenerator.cc.o
.PHONY : src/cosmicsEventGenerator.cc.o

src/cosmicsEventGenerator.i: src/cosmicsEventGenerator.cc.i
.PHONY : src/cosmicsEventGenerator.i

# target to preprocess a source file
src/cosmicsEventGenerator.cc.i:
	$(MAKE) -f CMakeFiles/cosmicRayShower.dir/build.make CMakeFiles/cosmicRayShower.dir/src/cosmicsEventGenerator.cc.i
.PHONY : src/cosmicsEventGenerator.cc.i

src/cosmicsEventGenerator.s: src/cosmicsEventGenerator.cc.s
.PHONY : src/cosmicsEventGenerator.s

# target to generate assembly for a file
src/cosmicsEventGenerator.cc.s:
	$(MAKE) -f CMakeFiles/cosmicRayShower.dir/build.make CMakeFiles/cosmicRayShower.dir/src/cosmicsEventGenerator.cc.s
.PHONY : src/cosmicsEventGenerator.cc.s

src/cosmicsPhysicsList.o: src/cosmicsPhysicsList.cc.o
.PHONY : src/cosmicsPhysicsList.o

# target to build an object file
src/cosmicsPhysicsList.cc.o:
	$(MAKE) -f CMakeFiles/cosmicRayShower.dir/build.make CMakeFiles/cosmicRayShower.dir/src/cosmicsPhysicsList.cc.o
.PHONY : src/cosmicsPhysicsList.cc.o

src/cosmicsPhysicsList.i: src/cosmicsPhysicsList.cc.i
.PHONY : src/cosmicsPhysicsList.i

# target to preprocess a source file
src/cosmicsPhysicsList.cc.i:
	$(MAKE) -f CMakeFiles/cosmicRayShower.dir/build.make CMakeFiles/cosmicRayShower.dir/src/cosmicsPhysicsList.cc.i
.PHONY : src/cosmicsPhysicsList.cc.i

src/cosmicsPhysicsList.s: src/cosmicsPhysicsList.cc.s
.PHONY : src/cosmicsPhysicsList.s

# target to generate assembly for a file
src/cosmicsPhysicsList.cc.s:
	$(MAKE) -f CMakeFiles/cosmicRayShower.dir/build.make CMakeFiles/cosmicRayShower.dir/src/cosmicsPhysicsList.cc.s
.PHONY : src/cosmicsPhysicsList.cc.s

src/cosmicsRunAction.o: src/cosmicsRunAction.cc.o
.PHONY : src/cosmicsRunAction.o

# target to build an object file
src/cosmicsRunAction.cc.o:
	$(MAKE) -f CMakeFiles/cosmicRayShower.dir/build.make CMakeFiles/cosmicRayShower.dir/src/cosmicsRunAction.cc.o
.PHONY : src/cosmicsRunAction.cc.o

src/cosmicsRunAction.i: src/cosmicsRunAction.cc.i
.PHONY : src/cosmicsRunAction.i

# target to preprocess a source file
src/cosmicsRunAction.cc.i:
	$(MAKE) -f CMakeFiles/cosmicRayShower.dir/build.make CMakeFiles/cosmicRayShower.dir/src/cosmicsRunAction.cc.i
.PHONY : src/cosmicsRunAction.cc.i

src/cosmicsRunAction.s: src/cosmicsRunAction.cc.s
.PHONY : src/cosmicsRunAction.s

# target to generate assembly for a file
src/cosmicsRunAction.cc.s:
	$(MAKE) -f CMakeFiles/cosmicRayShower.dir/build.make CMakeFiles/cosmicRayShower.dir/src/cosmicsRunAction.cc.s
.PHONY : src/cosmicsRunAction.cc.s

src/cosmicsSensitiveDetector.o: src/cosmicsSensitiveDetector.cc.o
.PHONY : src/cosmicsSensitiveDetector.o

# target to build an object file
src/cosmicsSensitiveDetector.cc.o:
	$(MAKE) -f CMakeFiles/cosmicRayShower.dir/build.make CMakeFiles/cosmicRayShower.dir/src/cosmicsSensitiveDetector.cc.o
.PHONY : src/cosmicsSensitiveDetector.cc.o

src/cosmicsSensitiveDetector.i: src/cosmicsSensitiveDetector.cc.i
.PHONY : src/cosmicsSensitiveDetector.i

# target to preprocess a source file
src/cosmicsSensitiveDetector.cc.i:
	$(MAKE) -f CMakeFiles/cosmicRayShower.dir/build.make CMakeFiles/cosmicRayShower.dir/src/cosmicsSensitiveDetector.cc.i
.PHONY : src/cosmicsSensitiveDetector.cc.i

src/cosmicsSensitiveDetector.s: src/cosmicsSensitiveDetector.cc.s
.PHONY : src/cosmicsSensitiveDetector.s

# target to generate assembly for a file
src/cosmicsSensitiveDetector.cc.s:
	$(MAKE) -f CMakeFiles/cosmicRayShower.dir/build.make CMakeFiles/cosmicRayShower.dir/src/cosmicsSensitiveDetector.cc.s
.PHONY : src/cosmicsSensitiveDetector.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... cosmicRayShower"
	@echo "... cosmics"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... cosmicRayShower.o"
	@echo "... cosmicRayShower.i"
	@echo "... cosmicRayShower.s"
	@echo "... src/cosmicsEventGenerator.o"
	@echo "... src/cosmicsEventGenerator.i"
	@echo "... src/cosmicsEventGenerator.s"
	@echo "... src/cosmicsPhysicsList.o"
	@echo "... src/cosmicsPhysicsList.i"
	@echo "... src/cosmicsPhysicsList.s"
	@echo "... src/cosmicsRunAction.o"
	@echo "... src/cosmicsRunAction.i"
	@echo "... src/cosmicsRunAction.s"
	@echo "... src/cosmicsSensitiveDetector.o"
	@echo "... src/cosmicsSensitiveDetector.i"
	@echo "... src/cosmicsSensitiveDetector.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

