# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/cmake-gui

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/sakib/remoll/cosmic/CosmicRayShowerv1

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/sakib/remoll/cosmic/CosmicRayShowerv1

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/cmake-gui -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local
.PHONY : install/local/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/sakib/remoll/cosmic/CosmicRayShowerv1/CMakeFiles /home/sakib/remoll/cosmic/CosmicRayShowerv1/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/sakib/remoll/cosmic/CosmicRayShowerv1/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named cosmic

# Build rule for target.
cosmic: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cosmic
.PHONY : cosmic

# fast build rule for target.
cosmic/fast:
	$(MAKE) -f CMakeFiles/cosmic.dir/build.make CMakeFiles/cosmic.dir/build
.PHONY : cosmic/fast

#=============================================================================
# Target rules for targets named cosmicRayShower

# Build rule for target.
cosmicRayShower: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cosmicRayShower
.PHONY : cosmicRayShower

# fast build rule for target.
cosmicRayShower/fast:
	$(MAKE) -f CMakeFiles/cosmicRayShower.dir/build.make CMakeFiles/cosmicRayShower.dir/build
.PHONY : cosmicRayShower/fast

# Manual pre-install relink rule for target.
cosmicRayShower/preinstall:
	$(MAKE) -f CMakeFiles/cosmicRayShower.dir/build.make CMakeFiles/cosmicRayShower.dir/preinstall
.PHONY : cosmicRayShower/preinstall

cosmicRayShower.o: cosmicRayShower.cc.o
.PHONY : cosmicRayShower.o

# target to build an object file
cosmicRayShower.cc.o:
	$(MAKE) -f CMakeFiles/cosmicRayShower.dir/build.make CMakeFiles/cosmicRayShower.dir/cosmicRayShower.cc.o
.PHONY : cosmicRayShower.cc.o

cosmicRayShower.i: cosmicRayShower.cc.i
.PHONY : cosmicRayShower.i

# target to preprocess a source file
cosmicRayShower.cc.i:
	$(MAKE) -f CMakeFiles/cosmicRayShower.dir/build.make CMakeFiles/cosmicRayShower.dir/cosmicRayShower.cc.i
.PHONY : cosmicRayShower.cc.i

cosmicRayShower.s: cosmicRayShower.cc.s
.PHONY : cosmicRayShower.s

# target to generate assembly for a file
cosmicRayShower.cc.s:
	$(MAKE) -f CMakeFiles/cosmicRayShower.dir/build.make CMakeFiles/cosmicRayShower.dir/cosmicRayShower.cc.s
.PHONY : cosmicRayShower.cc.s

src/cosmicDetectorConstruction.o: src/cosmicDetectorConstruction.cc.o
.PHONY : src/cosmicDetectorConstruction.o

# target to build an object file
src/cosmicDetectorConstruction.cc.o:
	$(MAKE) -f CMakeFiles/cosmicRayShower.dir/build.make CMakeFiles/cosmicRayShower.dir/src/cosmicDetectorConstruction.cc.o
.PHONY : src/cosmicDetectorConstruction.cc.o

src/cosmicDetectorConstruction.i: src/cosmicDetectorConstruction.cc.i
.PHONY : src/cosmicDetectorConstruction.i

# target to preprocess a source file
src/cosmicDetectorConstruction.cc.i:
	$(MAKE) -f CMakeFiles/cosmicRayShower.dir/build.make CMakeFiles/cosmicRayShower.dir/src/cosmicDetectorConstruction.cc.i
.PHONY : src/cosmicDetectorConstruction.cc.i

src/cosmicDetectorConstruction.s: src/cosmicDetectorConstruction.cc.s
.PHONY : src/cosmicDetectorConstruction.s

# target to generate assembly for a file
src/cosmicDetectorConstruction.cc.s:
	$(MAKE) -f CMakeFiles/cosmicRayShower.dir/build.make CMakeFiles/cosmicRayShower.dir/src/cosmicDetectorConstruction.cc.s
.PHONY : src/cosmicDetectorConstruction.cc.s

src/cosmicEventAction.o: src/cosmicEventAction.cc.o
.PHONY : src/cosmicEventAction.o

# target to build an object file
src/cosmicEventAction.cc.o:
	$(MAKE) -f CMakeFiles/cosmicRayShower.dir/build.make CMakeFiles/cosmicRayShower.dir/src/cosmicEventAction.cc.o
.PHONY : src/cosmicEventAction.cc.o

src/cosmicEventAction.i: src/cosmicEventAction.cc.i
.PHONY : src/cosmicEventAction.i

# target to preprocess a source file
src/cosmicEventAction.cc.i:
	$(MAKE) -f CMakeFiles/cosmicRayShower.dir/build.make CMakeFiles/cosmicRayShower.dir/src/cosmicEventAction.cc.i
.PHONY : src/cosmicEventAction.cc.i

src/cosmicEventAction.s: src/cosmicEventAction.cc.s
.PHONY : src/cosmicEventAction.s

# target to generate assembly for a file
src/cosmicEventAction.cc.s:
	$(MAKE) -f CMakeFiles/cosmicRayShower.dir/build.make CMakeFiles/cosmicRayShower.dir/src/cosmicEventAction.cc.s
.PHONY : src/cosmicEventAction.cc.s

src/cosmicPrimaryGeneratorAction.o: src/cosmicPrimaryGeneratorAction.cc.o
.PHONY : src/cosmicPrimaryGeneratorAction.o

# target to build an object file
src/cosmicPrimaryGeneratorAction.cc.o:
	$(MAKE) -f CMakeFiles/cosmicRayShower.dir/build.make CMakeFiles/cosmicRayShower.dir/src/cosmicPrimaryGeneratorAction.cc.o
.PHONY : src/cosmicPrimaryGeneratorAction.cc.o

src/cosmicPrimaryGeneratorAction.i: src/cosmicPrimaryGeneratorAction.cc.i
.PHONY : src/cosmicPrimaryGeneratorAction.i

# target to preprocess a source file
src/cosmicPrimaryGeneratorAction.cc.i:
	$(MAKE) -f CMakeFiles/cosmicRayShower.dir/build.make CMakeFiles/cosmicRayShower.dir/src/cosmicPrimaryGeneratorAction.cc.i
.PHONY : src/cosmicPrimaryGeneratorAction.cc.i

src/cosmicPrimaryGeneratorAction.s: src/cosmicPrimaryGeneratorAction.cc.s
.PHONY : src/cosmicPrimaryGeneratorAction.s

# target to generate assembly for a file
src/cosmicPrimaryGeneratorAction.cc.s:
	$(MAKE) -f CMakeFiles/cosmicRayShower.dir/build.make CMakeFiles/cosmicRayShower.dir/src/cosmicPrimaryGeneratorAction.cc.s
.PHONY : src/cosmicPrimaryGeneratorAction.cc.s

src/cosmicRunAction.o: src/cosmicRunAction.cc.o
.PHONY : src/cosmicRunAction.o

# target to build an object file
src/cosmicRunAction.cc.o:
	$(MAKE) -f CMakeFiles/cosmicRayShower.dir/build.make CMakeFiles/cosmicRayShower.dir/src/cosmicRunAction.cc.o
.PHONY : src/cosmicRunAction.cc.o

src/cosmicRunAction.i: src/cosmicRunAction.cc.i
.PHONY : src/cosmicRunAction.i

# target to preprocess a source file
src/cosmicRunAction.cc.i:
	$(MAKE) -f CMakeFiles/cosmicRayShower.dir/build.make CMakeFiles/cosmicRayShower.dir/src/cosmicRunAction.cc.i
.PHONY : src/cosmicRunAction.cc.i

src/cosmicRunAction.s: src/cosmicRunAction.cc.s
.PHONY : src/cosmicRunAction.s

# target to generate assembly for a file
src/cosmicRunAction.cc.s:
	$(MAKE) -f CMakeFiles/cosmicRayShower.dir/build.make CMakeFiles/cosmicRayShower.dir/src/cosmicRunAction.cc.s
.PHONY : src/cosmicRunAction.cc.s

src/cosmicSteppingAction.o: src/cosmicSteppingAction.cc.o
.PHONY : src/cosmicSteppingAction.o

# target to build an object file
src/cosmicSteppingAction.cc.o:
	$(MAKE) -f CMakeFiles/cosmicRayShower.dir/build.make CMakeFiles/cosmicRayShower.dir/src/cosmicSteppingAction.cc.o
.PHONY : src/cosmicSteppingAction.cc.o

src/cosmicSteppingAction.i: src/cosmicSteppingAction.cc.i
.PHONY : src/cosmicSteppingAction.i

# target to preprocess a source file
src/cosmicSteppingAction.cc.i:
	$(MAKE) -f CMakeFiles/cosmicRayShower.dir/build.make CMakeFiles/cosmicRayShower.dir/src/cosmicSteppingAction.cc.i
.PHONY : src/cosmicSteppingAction.cc.i

src/cosmicSteppingAction.s: src/cosmicSteppingAction.cc.s
.PHONY : src/cosmicSteppingAction.s

# target to generate assembly for a file
src/cosmicSteppingAction.cc.s:
	$(MAKE) -f CMakeFiles/cosmicRayShower.dir/build.make CMakeFiles/cosmicRayShower.dir/src/cosmicSteppingAction.cc.s
.PHONY : src/cosmicSteppingAction.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... cosmic"
	@echo "... cosmicRayShower"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... cosmicRayShower.o"
	@echo "... cosmicRayShower.i"
	@echo "... cosmicRayShower.s"
	@echo "... src/cosmicDetectorConstruction.o"
	@echo "... src/cosmicDetectorConstruction.i"
	@echo "... src/cosmicDetectorConstruction.s"
	@echo "... src/cosmicEventAction.o"
	@echo "... src/cosmicEventAction.i"
	@echo "... src/cosmicEventAction.s"
	@echo "... src/cosmicPrimaryGeneratorAction.o"
	@echo "... src/cosmicPrimaryGeneratorAction.i"
	@echo "... src/cosmicPrimaryGeneratorAction.s"
	@echo "... src/cosmicRunAction.o"
	@echo "... src/cosmicRunAction.i"
	@echo "... src/cosmicRunAction.s"
	@echo "... src/cosmicSteppingAction.o"
	@echo "... src/cosmicSteppingAction.i"
	@echo "... src/cosmicSteppingAction.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

